name: expenses_off
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  equatable: ^2.0.5
  dio: ^4.0.6
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  internet_connection_checker_plus: ^2.0.0
  intl: ^0.18.1
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/