// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSYf4HgE5ejKRzyfZDX_1NcGPVKWHItSc',
    appId: '1:598663851122:web:185d239f738760d44c26eb',
    messagingSenderId: '598663851122',
    projectId: 'expenseoff',
    authDomain: 'expenseoff.firebaseapp.com',
    storageBucket: 'expenseoff.appspot.com',
    measurementId: 'G-M0BQCHEFSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4g6yYZ5YxSHCX-seUDg-Og2vlPTNnrCo',
    appId: '1:598663851122:android:c333f230e42bc7884c26eb',
    messagingSenderId: '598663851122',
    projectId: 'expenseoff',
    storageBucket: 'expenseoff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMBJ0jHf6oWi6Et6KMVLWEP0eSh3SLC5Q',
    appId: '1:598663851122:ios:e206610e5171fe9f4c26eb',
    messagingSenderId: '598663851122',
    projectId: 'expenseoff',
    storageBucket: 'expenseoff.appspot.com',
    iosBundleId: 'com.expensesoff.expensesOff',
  );
}
